name: CI

on:
  push:
    branches:
      - main
      - yamibo
    paths:
      - "**"
      - "!**.md"
      - "!.github/**"
      - ".github/scripts/**"
      - ".github/workflows/build_push.yml"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 1
  IS_PR_CHECK: false

jobs:
  build:
    name: Build extensions (${{ matrix.chunk.number }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout main branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set extVersionCode to ${{ github.run_number }}
        run: |
          sed -i 's/extVersionCode = 1/extVersionCode = '${{ github.run_number }}'/' src/zh/yamibo/build.gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-read-only: ${{ matrix.chunk.number > 1 }}

      - name: Prepare signing key
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

      - name: Build extensions (${{ matrix.chunk.number }})
        env:
          MODULES: ${{ join(matrix.chunk.modules, ' ') }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew src:zh:yamibo:assembleRelease

      - name: Clean up CI files
        run: rm signingkey.jks

      - name: Move APKs
        run: |
          mv src/zh/yamibo/build/outputs/apk/release/*.apk .

      - name: Upload APKs (chunk ${{ matrix.chunk }})
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: "individual-apks-${{ matrix.chunk }}"
          path: "*.apk"

      - name: Create tag
        run: |
          git tag rel-${{ github.run_number }}
          git push origin --tags

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: rel-${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          files: "*.apk"

      - uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
